# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := lass parser muparser lcmod cmod UpgradeProjectFormat lassie

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

lass: 
	@echo "==== Building lass ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f lass.make

parser: 
	@echo "==== Building parser ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f parser.make

muparser: 
	@echo "==== Building muparser ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f muparser.make

lcmod: 
	@echo "==== Building lcmod ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f lcmod.make

cmod: lcmod lass parser muparser
	@echo "==== Building cmod ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f cmod.make

UpgradeProjectFormat: lcmod lass parser muparser
	@echo "==== Building UpgradeProjectFormat ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f UpgradeProjectFormat.make

lassie: lcmod lass parser
	@echo "==== Building lassie ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f lassie.make

clean:
	@${MAKE} --no-print-directory -C . -f lass.make clean
	@${MAKE} --no-print-directory -C . -f parser.make clean
	@${MAKE} --no-print-directory -C . -f muparser.make clean
	@${MAKE} --no-print-directory -C . -f lcmod.make clean
	@${MAKE} --no-print-directory -C . -f cmod.make clean
	@${MAKE} --no-print-directory -C . -f UpgradeProjectFormat.make clean
	@${MAKE} --no-print-directory -C . -f lassie.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lass"
	@echo "   parser"
	@echo "   muparser"
	@echo "   lcmod"
	@echo "   cmod"
	@echo "   UpgradeProjectFormat"
	@echo "   lassie"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
